<?php 
    // titolo della pagina
    $titolo_pagina = "Bonus Idrico";
    include("template/titolo_pagina.php"); 
?>
<div style="line-height:1.8;"align="justify">
    <br>
    <h4>CHE COS'È IL BONUS IDRICO O BONUS ACQUA?</h4>
        <p>Dal 1 luglio 2018 sarà possibile richiedere il bonus sociale idrico o bonus acqua per la fornitura di acqua.<br>Si tratta di una misura volta a ridurre la spesa per il servizio di acquedotto di una famiglia in condizione di disagio economico e sociale.</p>
        <p>È stata prevista dal decreto del Presidente del Consiglio dei ministri 13 ottobre 2016, emanato in forza dell'articolo 60 del cosiddetto Collegato Ambientale (legge 28 dicembre 2015, n. 221) e successivamente attuata con provvedimenti dell'Autorità di Regolazione per Energia Reti e Ambiente.</p>
        <p>Consente di non pagare un quantitativo minimo di acqua a persona per anno. Tale quantitativo è stato fissato in 50 litri giorno a persona (18,25 mc di acqua all'anno), corrispondenti al soddisfacimento dei bisogni essenziali.</p>
        <p><b>Chi ne ha diritto?</b><br>Hanno diritto ad ottenere il bonus acqua gli utenti diretti ed indiretti del servizio di acquedotto in condizioni di disagio economico sociale, cioè che sono parte di nuclei familiari:</p>
    <ul>
        <li>con indicatore ISEE non superiore a 8.107,5 euro;
        <li>con indicatore ISEE non superiore a 20.000 euro se con almeno 4 figli a carico.
    </ul>
        <p><b>Chi è l'utente diretto?</b><br>E’ l’utente finale in condizioni di disagio economico sociale direttamente titolare di una fornitura per il servizio di acquedotto ad uso domestico residente.</p>
        <p><b>Chi è l'utente indiretto?</b><br>E’ uno dei componenti del nucleo ISEE in condizioni di disagio economico sociale, che utilizzi nell’abitazione di residenza una fornitura per il servizio di acquedotto intestata ad un’utenza condominiale.</p>
    <h4>Come e dove si richiede</h4>
        <p><b>Dove si presenta la domanda?</b><br>La domanda per ottenere il bonus acqua va presentata, in forma di autocertificazione, presso il proprio Comune di residenza o presso un altro ente designato dal Comune (CAF, Comunità montane) utilizzando gli appositi moduli che verranno pubblicati su questo sito (<a href="https://www.arera.it/it/index.htm"target="_blank">www.arera.it</a>), sul sito <a href="https://www.sgate.anci.it/"target="_blank">www.sgate.anci.it</a> e resi disponibili sui siti internet dei Gestori e degli Enti di Governo dell’Ambito.</p>
        <p><b>Quali documenti servono per presentare la domanda?</b><br>Per presentare la domanda, oltre al modulo compilato con i propri dati anagrafici e i riferimenti che identificano la fornitura, servono:</p>
    <ul>
        <li>un documento di identità;
        <li>un'eventuale delega;
        <li>un'attestazione ISEE in corso di validità;
        <li>un'attestazione che contenga i dati di tutti i componenti del nucleo ISEE (nome-cognome e codice fiscale);
        <li>un'attestazione per il riconoscimento di famiglia numerosa (almeno 4 figli a carico), se l'ISEE è superiore a 8.107,5 euro (ma entro i 20.000 euro).
    </ul>
        <p>Le informazioni per identificare la fornitura sono reperibili in bolletta e sono:</p>
    <ul>
        <li>il codice fornitura;
        <li>il nominativo del gestore idrico (il soggetto che gestisce il servizio di acquedotto e che emette la fattura).
    </ul>
        <p>Nel caso di un utente indiretto queste ultime due informazioni non sono obbligatorie, ma è assolutamente preferibile averle a disposizione al momento della presentazione della domanda.</p>
        <p><b>È possibile delegare una terza persona per presentare la domanda?</b><br>Sì, compilando un’apposita delega con le generalità della persona che si vuole delegare.</p>
        <p><b>Posso richiedere il bonus acqua insieme a quello per energia elettrica e gas?</b><br>Si, il modulo di richiesta, che verrà pubblicato su questo sito (<a href="https://www.arera.it/it/index.htm"target="_blank">www.arera.it</a>), sul sito <a href="https://www.sgate.anci.it/"target="_blank">www.sgate.anci.it</a> e reso disponibile sui siti internet dei Gestori e degli Enti di Governo dell’Ambito, permette di richiedere contemporaneamente anche il bonus elettrico e/o gas.</p>
        <p><b>Ho già il bonus elettrico/gas, come posso allineare le diverse scadenze?</b><br>Agli utenti che al momento della presentazione della domanda per il bonus acqua risulteranno già titolari di un bonus elettrico e/o gas richiesto o rinnovato nel 2018 in modo congiunto (una sola domanda presentata contemporaneamente per il bonus elettrico e gas) o disgiunto (due domande presentate in tempi diversi), verrà riconosciuto un periodo di agevolazione per il bonus idrico allineato al periodo di agevolazione del bonus elettrico e/o gas. Ad esempio:</p>
    <ul>
        <li>se la domanda elettrica e gas é stata presentata congiuntamente, il periodo di agevolazione del bonus idrico sarà ricondotto a quello dei bonus elettrico e gas. Ad esempio, se il periodo di agevolazione del bonus elettrico e gas decorre dal 1° aprile 2018 al 31 marzo 2019, anche il periodo di agevolazione per il bonus acqua avrà decorrenza 1° aprile 2018 – 31 marzo 2019 anche se la domanda per quest’ultimo viene presentata dopo il 1 luglio;
        <li>se le domande di bonus elettrico e gas sono state presentate in momenti diversi nel corso del 2018, quindi sono disgiunte, il periodo di decorrenza del bonus idrico sarà allineato solo a uno dei due bonus già presentati ed in particolare al più recente. Ad esempio, se la decorrenza del bonus elettrico è 1° aprile 2018 - 31 marzo 2019, e quella del bonus gas è 1° giugno 2018 - 31 maggio 2019, il riallineamento del periodo di agevolazione per la domanda idrica verrà operato prendendo a riferimento il bonus gas (domanda più recente).
    </ul>
        <p><b><i>IMPORTANTE:</i></b> Il gestore del servizio di acquedotto riconoscerà all’utente, per il solo 2018, oltre al bonus acqua per tutto il periodo di agevolazione individuato secondo le modalità sopra indicate, anche una quota compensativa una tantum per il periodo compreso fra il 1° gennaio 2018 e l’inizio dell’effettivo periodo di agevolazione. Nel caso dell’esempio sopra riportato (periodo di agevolazione: 1° giugno 2018 – 31 maggio 2019), la quota una tantum coprirà il periodo 1° gennaio 2018- 31 maggio 2018.<br>Anche se l’utente presenta la sola domanda idrica la quota una tantum coprirà il periodo compreso fra il 1° gennaio 2018 e l’inizio del periodo di agevolazione che, in questo caso, sarà successivo al 1 luglio 2018.<br>vedi anche : Chiarimenti su erogazione della componente una tantum del bonus idrico per l'anno 2018.</p>
    <h4>Quanto vale il bonus e come si riceve</h4>
        <p><b>Quanto vale il bonus acqua?</b><br>Il bonus acqua garantisce la fornitura gratuita di 18,25 metri cubi di acqua su base annua (pari a 50 litri/abitante/giorno) per ogni componente della famiglia anagrafica dell’utente. Tale quantità è stata individuata dal decreto del Presidente del Consiglio dei ministri 13 ottobre 2016 come quella minima necessaria per assicurare il soddisfacimento dei bisogni fondamentali della persona.<br>Il bonus garantirà, ad esempio, ad una famiglia di 4 persone di non dover pagare 73 metri cubi di acqua all’anno.La tariffa agevolata applicata dal gestore non è unica a livello nazionale, quindi per individuare quale sia il corrispettivo (tariffa agevolata) che deve essere applicato ai 18,25 metri cubi e conoscere il valore del bonus, l’utente potrà consultare il sito del proprio gestore su cui saranno pubblicate le informazioni relative alla tariffa agevolata applicata e calcolare l’importo del bonus acqua a cui ha diritto.</p>
        <p><b>Come viene corrisposto il bonus?</b><br>L'erogazione del bonus acqua avviene con modalità differenti:</p>
    <ul>
        <li>Per gli utenti diretti, l'erogazione avviene in bolletta. Nello specifico, l'ammontare annuo è erogato pro-quota giorno e ogni bolletta che contabilizzi i consumi relativi al periodo di agevolazione riporterà una parte del bonus proporzionale al periodo cui la bolletta medesima fa riferimento.
        <li>Per gli utenti indiretti, il gestore provvederà ad erogare il bonus in un’unica soluzione, ad esempio mediante accredito sul conto corrente (bancario o postale) o con un assegno circolare non trasferibile o con qualsiasi altra modalità scelta dal gestore, purché tracciabile e quindi verificabile.
    </ul>
        <p><b>Come si verifica se la propria domanda di bonus acqua è andata a buon fine?</b><br>In generale è possibile verificare lo stato di avanzamento della propria richiesta di bonus utilizzando i riferimenti presenti nella comunicazione di ammissione che viene inviata all’utente oppure:</p>
    <ul>
        <li>rivolgendosi all'Ente al quale è stata presentata la richiesta (il Comune di residenza, il CAF, la Comunità Montana, ecc.) con la ricevuta rilasciata alla consegna della domanda;
        <li>chiamando il numero verde 800.166.654 dello Sportello per il consumatore di Energia e Ambiente e fornendo il codice fiscale o il numero identificativo della richiesta presente nella lettera di ammissione;
        <li>consultando il sito <a href="http://www.bonusenergia.anci.it/"target="_blank">www.bonusenergia.anci.it</a>, nella sezione riservata "Controlla on line la tua pratica", cui si accede con il proprio codice fiscale e le credenziali di accesso (User ID e password) comunicate nella lettera di ammissione.
    </ul>
        <p><b>Come si verifica se il bonus erogato è corretto?</b><br>Per verificare se il bonus erogato è corretto, gli utenti diretti possono controllare la loro bolletta e precisamente la sezione del quadro di sintesi dedicata al dettaglio delle singole voci che compongono il totale degli importi fatturati.<br> La componente bonus viene indicata separatamente in detrazione della quota variabile della tariffa di acquedotto per tutto il periodo di agevolazione.<br>Gli utenti indiretti possono verificare la correttezza controllando l’accredito, l’assegno o qualunque altra modalità di corresponsione utilizzata dal gestore per l’effettiva erogazione.</p>
        <p><b>Dopo quanto tempo dalla presentazione della domanda mi verrà corrisposto il bonus?</b><br>Dal momento della presentazione della domanda al momento dell’erogazione del bonus acqua possono passare diversi mesi.<br>Infatti dopo aver presentato la domanda di bonus al proprio Comune di residenza o ai CAF abilitati, le tempistiche per ottenere il bonus sono così cadenzate:</p>
    <ul>
        <li>Il Comune ha a disposizione un massimo di 30 giorni per la verifica e l’ammissione della domanda con il suo successivo caricamento nel sistema informatico (SGAte) per la trasmissione al gestore;
        <li>Dopo il caricamento da parte del Comune della domanda ammessa:
        <ul>
            <li>L’utente riceve una comunicazione che lo informa dei risultati delle prime valutazioni sui requisiti di ammissibilità (ISEE e residenza) operate dal Comune;
            <li>Il gestore ha a disposizione un massimo di 60 giorni per completare le valutazioni di sua competenza e comunicare a SGAte l’ammissione definitiva della domanda o il suo rigetto.
        </ul>
    </ul>
        <p>Al termine di questi 60 giorni, se la domanda è stata verificata positivamente dal gestore:</p>
    <ul>
        <li>gli utenti diretti, riceveranno il bonus in bolletta nella prima fattura utile. Le tempistiche di erogazione del bonus in bolletta dipenderanno anche dalla periodicità di fatturazione prevista dal contratto di fornitura;
        <li>gli utenti indiretti riceveranno il bonus entro un periodo massimo di ulteriori 60 giorni.
    </ul>    
        <p>Tutti gli utenti, la cui domanda risulterà respinta, riceveranno una comunicazione con l’indicazione del motivo per cui il gestore non ha potuto confermare l’ammissione.</p>
        <p><b>Per quanto tempo viene riconosciuto il bonus?</b><br>Il bonus è riconosciuto per un periodo di 12 mesi a decorrere dalla data di inizio agevolazione riportata nella comunicazione di ammissione e in bolletta.<br> Al termine di tale periodo, per ottenere un nuovo bonus, l’utente deve rinnovare la richiesta di ammissione presentando apposita domanda.</p>
        <p><b>Quali problemi potrebbero verificarsi nella gestione della pratica di bonus?</b><br>Come per i bonus elettrico e gas, anche per il bonus acqua le pratiche saranno gestite mediante il sistema informatico SGAte, cui accedono i Comuni e i CAF delegati. Oltre ai Comuni e ai CAF abilitati, hanno l’obbligo di accreditarsi al sistema SGAte anche i gestori del servizio di acquedotto. Infatti, se un gestore non si accredita, SGAte non riesce a trasferirgli la pratica per le verifiche di sua competenza e per l’erogazione del bonus.</p>
        <p>Nei casi di mancato accreditamento del gestore gli utenti interessati riceveranno, pertanto, una comunicazione con la quale verranno informati che hanno i requisiti per richiedere il bonus (ISEE entro la soglia) ma per ottenerlo devono rivolgersi direttamente al proprio gestore (che dovrà effettuare i controlli di propria competenza) nei punti di contatto da quest’ultimo predisposti per l’utenza (sportelli fisici o sito web).</p>
    <h4>Rinnovo e variazioni</h4>
        <p><b>Come si rinnova la domanda di bonus?</b><br>Se al termine del periodo di prima agevolazione l’utente ha ancora i requisiti necessari per l’ammissione (ISEE entro la soglia stabilita, presenza di un contratto di fornitura per il servizio di acquedotto presso l’abitazione di residenza) può rinnovare la richiesta di bonus presentando apposita domanda presso il Comune di residenza o i CAF abilitati.<br>La domanda va presentata circa un mese prima della scadenza dell'agevolazione in corso (se, ad esempio, il periodo di agevolazione va dal 1-9-2018 al 31-08-2019, il rinnovo deve essere presentato entro il 30 luglio 2019) al fine di garantire la continuità dell'erogazione. Un'apposita comunicazione viene inviata a tutti gli utenti interessati in prossimità della scadenza, per ricordare la data utile per il rinnovo in continuità.<br>Al momento del rinnovo l’utente deve presentare un'attestazione ISEE valida per il periodo da cui decorre la nuova agevolazione.<br>Con riferimento all’esempio precedente, il certificato ISEE dovrà essere valido anche il 1 settembre 2019.</p>
        <p><b>Cosa bisogna fare in caso di variazioni del numero di familiari durante il periodo di agevolazione?</b><br>Le variazioni della numerosità familiare, che avvengono durante il periodo di agevolazione, possono essere comunicate al momento del rinnovo e hanno validità ai fini del calcolo del bonus per il nuovo periodo di agevolazione.<br>Tuttavia se l’utente presenta al proprio gestore idrico, durante i 12 mesi di vigenza del bonus, un’autocertificazione ai sensi del DPR 445/2000 di variazione del numero dei componenti la famiglia e dichiara che tale variazione non modifica la condizione di disagio economico, (ossia l’ISEE resta ricompreso entro la soglia limite), il gestore adeguerà il corrispettivo del bonus alla nuova numerosità familiare per il periodo che manca al termine dei 12 mesi di vigenza dell’agevolazione.</p>
        <p><b>Cosa succede in caso di cambio dell’indirizzo di residenza o di cessazione del contratto?</b><br>Nel caso in cui durante il periodo di agevolazione cessi il contratto di fornitura intestato all’utente agevolato (ad esempio per cambio di residenza o per altre ragioni), il gestore corrisponderà nella fattura di chiusura la quota di bonus spettante e non ancora erogata a copertura del restante periodo di agevolazione.<br>Ad esempio, se il periodo di agevolazione è 1° settembre 2018- 31 agosto 2019 e l’utente cambia residenza ad aprile 2019, riceverà, nella fattura di chiusura della fornitura che cessa per cambio residenza, l’ammontare di bonus previsto fino al 31 agosto 2019.<br>Né l’utente interessato né alcuno dei componenti del suo nucleo ISEE potranno presentare una nuova domanda di bonus acqua prima del termine dell’originario periodo di agevolazione.
    <h4>Bonus integrativo locale</h4>
        <p><b>Che cosa è il bonus integrativo?</b><br>E’ un’agevolazione migliorativa stabilita a livello locale: può comportare il riconoscimento di un beneficio economico aggiuntivo o diverso rispetto al bonus acqua. Ad esempio l’Ente di governo dell’Ambito (EGA) competente per il proprio territorio può decidere di riconoscere all’utente finale, a parità di condizioni di ammissione, un bonus acqua maggiore rispetto a quanto previsto a livello nazionale o può modificare in meglio le condizioni di ammissione innalzando la soglia massima di ISEE prevista.<br>I requisiti di ammissione e la quantificazione del bonus integrativo sono pertanto decisi a livello locale e possono differire da quanto stabilito a livello nazionale.</p>
        <p><b>Il mio gestore erogava già il bonus, posso continuare a richiederlo?</b><br>Dipende dal gestore e dall’Ente di Governo dell’Ambito. Infatti sul suo territorio il gestore in accordo con l’EGA può decidere liberamente se continuare o meno ad applicare le condizioni di miglior favore già previste per i propri utenti.</p>
        <p><b>Chi ne ha diritto? Dove e come si può fare richiesta? Quanto vale?</b><br>I requisiti per accedere al bonus acqua integrativo (livello ISEE o altro), come si richiede e quanto vale sono stabiliti in modo autonomo dal gestore in accordo con l’EGA; per avere maggiori informazioni occorre rivolgersi al proprio gestore.</p>
</div>